apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}

          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html

            - name: nginx-config
              mountPath: /etc/nginx/conf.d

          resources:
            requests:
              cpu: {{ .Values.resources.frontend.requests.cpu }}
              memory: {{ .Values.resources.frontend.requests.memory }}
            limits:
              cpu: {{ .Values.resources.frontend.limits.cpu }}
              memory: {{ .Values.resources.frontend.limits.memory }}

      volumes:
        - name: html
          configMap:
            name: frontend-html

        - name: nginx-config
          configMap:
            name: nginx-config